#!/bin/sh

set -e

JAVA_VERSION=7u3 #must be modified for each release
FILENAME=jdk-${JAVA_VERSION}-linux-${dld}.tar.gz
case $(uname -m) in
  'i686'    ) SHA256SUM_TGZ="798a3ea1d390358bdc01911d9aab7da1ff887157b56becc0e07e6f2c031f9ded";; #must be modified for each release
  'x86_64'  ) SHA256SUM_TGZ="28ff4bc3194617e0f6144013b1ca391b279804170e297faa6879963424846c2d";; #must be modified for each release
  *         )
    echo "Please report to author unsupported platform '`uname -m`'.";
    echo "Proceeding without web browser plugin support";
esac
PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/7u3-b04/$FILENAME #must be modified for each release!!!
COOKIE_URL=http://launchpadlibrarian.net/98645053/cookie.txt #required by the latest JDK7, wget doesn't work without it
J_INSTALL_DIR=/usr/lib/jvm/java-7-oracle
J_DIR=jdk1.7.0_03 #must be modified for each release

. /usr/share/debconf/confmodule

db_get oracle-java7-installer/local
echo "$SHA256SUM_TGZ  $RET/$FILENAME" \
| sha256sum -c > /dev/null 2>&1 \
|| db_set oracle-java7-installer/local /var/cache/oracle-jdk7-installer

db_get oracle-java7-installer/local
echo "$SHA256SUM_TGZ  $RET/$FILENAME" \
| sha256sum -c > /dev/null 2>&1 \
|| db_set oracle-java7-installer/local /usr/lib/oracle-jdk7-installer-unpackdir

db_get oracle-java7-installer/local
echo "$SHA256SUM_TGZ  $RET/$FILENAME" \
| sha256sum -c > /dev/null 2>&1 \
|| db_reset oracle-java7-installer/local 

while true; do
    db_input medium oracle-java7-installer/local || true
    db_go
    db_get oracle-java7-installer/local
    if [ -d "$RET" -a -f "$RET"/$FILENAME ]; then
		LOCAL="true"
		break;
    elif [ "x$RET" = "x" ]; then
		break;
    fi
    db_reset oracle-java7-installer/not_exist || true
    db_reset oracle-java7-installer/local || true
    db_text medium oracle-java7-installer/not_exist || true
    db_go
done

if [ "$LOCAL" != "true" ]; then
    db_reset oracle-java7-installer/httpget
    db_input medium oracle-java7-installer/httpget || true
    db_go
    db_get oracle-java7-installer/httpget
fi
